### ISSUE TITLE
Error placing order: ZiplineLog: Cannot place order for A, as it has de-listed. Any existing positions for this asset will be liquidated on 2017-

### ISSUE THREAD

**Issue by danielfppps** [zipline-live/zipline#45] opened 2017-08-23 15:42 UTC
Hi Guys,

I want to live-trade through IB but it seems that the way zipline is designed it does not allow me to enter orders for symbols for which I do not have a live-data feed coming in. If I try to do this then it complains about the symbol being "de-listed" and no "last price" being available. 

If I don't have a data subscription I still see no reason why I couldn't enter market orders for whatever symbol I want but zipline is very stubborn in that it only wants to allow me to trade symbols for which it knows the last-price and has a receiving real-time data-feed. 

Is there any way to overcome this?

Thanks in advance for your reply,

Best Regards,

Daniel

**Comment by tibkiss** [comment] 2017-08-23 16:17
I've faced this annoyance myself, the reason behind is that your bundle might not contain the symbol you are trying to trade. Could you please share which symbol was it?

I have worked around this issue by creating a custom data loader (using google finance), ingested the symbols of interest, then used that bundle.

**Comment by danielfppps** [comment] 2017-08-23 17:52
I was trying to trade MDY, which is not part of the quandl/quantopian bundle. I tried to do the same thing - add the symbol through google finance - but this does not work well as the data is not constantly updated and the program will complain about the symbol being "delisted" when attempting to live trade.

**Comment by tibkiss** [comment] 2017-08-23 19:14
@danielfppps : I'd suggest that you try the following:
every day you start your google ingestion at around 8AM, then start your algo. 

For me it has resolved the delisted trading problem.
Please let us know how it works.

**Comment by tibkiss** [comment] 2017-08-25 04:54
@danielfppps : did the daily ingestion solved the problem?

**Comment by danielfppps** [comment] 2017-08-25 12:06
Thanks for your help, sadly no. I finally decided against using zipline-live as the project overcomplicates things too much for my taste. For me it makes no sense to have to have all these issues with data ingestions, etc and not be able to simply say "BUY 5 shares of X at stock exchange Y". I moved to IBpy2 since it just makes more sense for my particular case. Thanks again for all the help though!

**Comment by tibkiss** [comment] 2017-08-29 17:38
Found the root cause of the issue, will post a PR with a fix soon.

**Comment by tibkiss** [comment] 2017-08-29 18:55
Associate PR is here: https://github.com/zipline-live/zipline/pull/55

**Comment by tibkiss** [comment] 2017-08-30 19:18
@danielfppps : A new release has been pushed to pypi which contains fix for this issue. Are you giving us a second chance and try it?

**Comment by danielfppps** [comment] 2017-08-30 19:22
Thanks a lot for effort :) I needed to implement a quick move away from quantopian so I ended up coding all the systems I needed using ibpy2. However I'm sure people using zipline-live will greatly appreciate your efforts!

**Comment by tibkiss** [comment] 2017-08-31 04:54
Thanks @danielfppps , good luck for the ibpy2 endeaveurs :)

**Closed by tibkiss** 2017-08-31 04:54 UTC
